default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  database: postgres
  port: 5434
  username: production
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: db/test.sqlite3


production:
  #<<: *default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  database: postgres
  port: 5434
  username: production
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>
