---
- Umschlag:
  - :gprods_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - true
    - true
    - false
    - false
  - :buecher_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
  - :status_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - 
    - false
    - true
- Bildprüfung:
  - :gprods_options:
    - false
    - false
    - false
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
  - :buecher_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
  - :status_options:
    - true
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - 
    - false
    - false
- Titelei:
  - :gprods_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - true
  - :buecher_options:
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - true
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
  - :status_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - 
    - true
    - false
- ExternerDruck:
  - :gprods_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - true
    - true
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
  - :buecher_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
  - :status_options:
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - 
    - false
    - false
- Rechnung:
  - :gprods_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
  - :buecher_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
  - :status_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - 
    - false
    - false
- Superadmin:
  - :gprods_options:
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
  - :buecher_options:
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - false
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - true
    - true
  - :status_options:
    - true
    - true
    - true
    - true
    - false
    - true
    - false
    - true
    - true
    - true
    - true
    - true
    - 
    - true
    - true
    - true
- Lektor:
  - :gprods_options:
    - true
    - true
    - true
    - true
    - false
    - true
    - false
    - true
    - false
    - true
    - false
    - false
    - true
    - false
    - true
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - true
    - true
    - true
    - true
    - true
    - false
    - true
    - false
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - true
    - true
    - false
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - true
    - false
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - true
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - true
    - true
    - true
    - true
    - true
    - false
  - :buecher_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - true
    - true
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
  - :status_options:
    - true
    - true
    - false
    - true
    - false
    - true
    - false
    - true
    - true
    - true
    - true
    - true
    - 
    - true
    - true
    - false
- Binderei:
  - :gprods_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
  - :buecher_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
  - :status_options:
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - 
    - false
    - false
- PrePs:
  - :gprods_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - true
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
  - :buecher_options:
    - false
    - false
    - false
    - true
    - true
    - true
    - true
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - true
    - false
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
  - :status_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - 
    - false
    - false
- Satz:
  - :gprods_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - true
    - false
    - false
    - false
    - false
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
  - :buecher_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - true
    - true
    - false
    - true
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
  - :status_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - 
    - false
    - false
- Pod:
  - :gprods_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - true
    - false
  - :buecher_options:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
  - :status_options:
    - false
    - false
    - true
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - 
    - false
    - false
