#Diese Variablen werden im Code verwendet NIEMALS 채ndern sonst muss man im gesamten Code die symbole 채ndern, sollen sie ge채ndert werden muss das Array in names: kopiert
#werden, dann bleiben die Namen im Code gleich und mann kann die optionen 채ndern.

options:
#True um die Option an zu schalten false um Sie zu deaktivieren
    binderei: [true,false]
    titelei: [true,true,true,true,true,true,true,true,true,true,true,true,true]
    satz:
    projekt:
    umschlag: [true,true,true,true,true,true,true,true,true,true,true,true,true,true, true, true]
    preps:


#Symbolnamen, die im Code verwendet werden sollen.
names:
    binderei: [Blub,bbkl]
    titelei: [statuschanger, titelei_bemerkungen, binderei_bemerkungen, titelei_zusaetze, kommentar_public, titelei_letzte_korrektur, titelei_versand_datum_fuer_ueberpr, titelei_versand_an_zur_ueberpf, titelei_korrektur_date, titelei_freigabe_date,format_bezeichnung,eintrag_cip_seite,erscheinungsjahr]
    satz:
    projekt:
    umschlag: [projektname, lektorname, isbn, final_deadline, kommentar_public, kommentar_umschlag, status_umschlag, umschlag_deadline, umschlag_bezeichnung, rueckenstaerke, format_bezeichnung, rueckenstaerke, seiten, bindung_bezeichnung, umschlagsbild, klappentext]
    preps:
