##
# That one says it all: app/models/concerns/choosable_option.rb
#
##
# Diese Variablen werden im Code verwendet NIEMALS ändern sonst muss man im
# gesamten Code die symbole ändern, sollen sie geändert werden muss das Array
# in names: kopiert werden, dann bleiben die Namen im Code gleich und mann kann
# die optionen ändern.
#
##
# Bullshit, we already have a perfectly fine global string variable class I18n
# and this guy here 'invented' a new one to make things less uniformly.
# Plus they are not used frequently only in very few spots.

options:
#Optionen für die Bucheigenschaften
    bindung_bezeichnung: [klebe,hardcover, fadenheftung, heft]
    prio: ['A','B','C','Z']
    form:
    datei:
    format_bezeichnung: ['A6', 'A5', 'A4', 'A3', '22', '23', '24', 'Sonder']
    umschlag_bezeichnung: ['wie Reihe', 'LaTeX', 'InDesign', 'Geliefert', 'neue Reihe']
    druck_art:
    vier_farb: ['1', '2', '3', '4']
    sonder:
    papier_bezeichnung: ['Offset 80g', 'Werkdruck 90g blau', 'Werkdruck 100g', 'Werkdruck 90g gelb']
    musterart:
    #Automische fristen ausgehen von Finaler Frist
    fristen: [5,6,7,8]

#Symbolnamen, die im Code verwendet werden sollen.
names:
#Optionen für die Bucheigenschaften
    bindung_bezeichnung: [klebe,hardcover, fadenheftung, heft]
    prio: ['a','b','c','z']
    form:
    datei:
    format_bezeichnung: ['a6', 'a5', 'a4', 'a3', '22', '23', '24', 'sonder']
    umschlag_bezeichnung: ['wiereihe', 'tex', 'indesign', 'extern', 'neu']
    druckart:
    vier_farb: ['1', '2', '3', '4']
    sonder:
    papier_bezeichnung: ['o80', 'w90', 'wg100', 'wg90']
    musterart:
    #Automische fristen ausgehen von Finaler Frist
    fristen: [titelei,preps,umschlag,binderei]
