class CreateNutzerrechte < ActiveRecord::Migration
  def change
    create_table :nutzerrechte do |t|
      t.string  :abteilung
      t.integer :name
      t.integer :isbn
      t.integer :auflage
      t.integer :prio
      t.integer :druck
      t.integer :msein
      t.integer :muster
      t.integer :offsch_sollf
      t.integer :einliste_sollf
      t.integer :sreif_sollf
      t.integer :lf_sollf
      t.integer :preps_sollf
      t.integer :tit_sollf
      t.integer :rg_sollf
      t.integer :rg_rg_mail
      t.integer :rg_versand_1
      t.integer :rg_versand_2
      t.integer :rg_bezahlt
      t.integer :rg_vf
      t.integer :datei
      t.integer :reihe
      t.integer :titelei
      t.integer :papier
      t.integer :gewicht
      t.integer :volumen
      t.integer :satz
      t.integer :sonder
      t.integer :datum
      t.integer :eintrag
      t.integer :versand
      t.integer :tit_an
      t.integer :korrektur
      t.integer :freigabe
      t.integer :zum_druck
      t.integer :erscheinungsjahr
      t.integer :tit_bemerkungen_1
      t.integer :tit_bemerkungen_2
      t.integer :lek
      t.integer :seiten
      t.integer :format
      t.integer :umschlag
      t.integer :bi
      t.integer :vf
      t.integer :preps_betreuer
      t.integer :korr_betreuer
      t.integer :preps_kommentar
      t.integer :tagesleistung
      t.integer :email
      t.integer :offsch_an_autor
      t.integer :offsch_an_sch_mit_u
      t.integer :is_archiv
      t.integer :cover
      t.integer :ebook_bemerkungen
      t.integer :ftp
      t.integer :webshop
      t.integer :google
      t.integer :afs
      t.integer :luecken
      t.integer :a1_dat
      t.integer :a2_dat
      t.integer :korr
      t.integer :anmerkung
      t.integer :pod_verschickt
      t.integer :pod_meldung
      t.integer :off
      t.integer :ein_liste_status
      t.integer :lf_status
      t.integer :sreif_status
      t.integer :um_status
      t.integer :tit_status
      t.integer :preps_status
      t.integer :bi_status
      t.integer :rg_status
      t.integer :ebook_status
      t.integer :korr_status
      t.integer :pod_status
      t.integer :tbl_ein_liste
      t.integer :tbl_lf
      t.integer :tbl_sreif
      t.integer :tbl_um
      t.integer :tbl_tit
      t.integer :tbl_preps
      t.integer :tbl_bi
      t.integer :tbl_rg
      t.integer :tbl_ebook
      t.integer :tbl_korr
      t.integer :tbl_pod
    end
  end
end
